#!/home/ubuntu/pdfenv/bin/python3
import sys
import os
import tempfile
import subprocess
from pathlib import Path

def convert_ppt_to_images(input_path, output_format="jpg", quality="high"):
    """
    Convert PowerPoint file to images using python-pptx and img2pdf
    """
    try:
        # Create temporary directory for output
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir_path = Path(temp_dir)
            
            # First convert PPT to PDF using LibreOffice
            pdf_path = temp_dir_path / "output.pdf"
            
            # Convert using LibreOffice
            lo_result = subprocess.run([
                "soffice", "--headless", "--convert-to", "pdf",
                input_path, "--outdir", str(temp_dir_path)
            ], capture_output=True, text=True, timeout=300)
            
            if lo_result.returncode != 0:
                raise Exception(f"LibreOffice conversion failed: {lo_result.stderr}")
            
            # Find the generated PDF file
            pdf_files = list(temp_dir_path.glob("*.pdf"))
            if not pdf_files:
                raise Exception("No PDF file was generated by LibreOffice")
            
            pdf_path = pdf_files[0]
            
            # Set quality parameters
            quality_map = {
                "high": "95",
                "medium": "80",
                "low": "65"
            }
            quality_value = quality_map.get(quality, "95")
            
            # Convert PDF to images using pdftoppm (from poppler-utils)
            output_prefix = temp_dir_path / "slide"
            
            if output_format.lower() in ["jpg", "jpeg"]:
                format_flag = "-jpeg"
                extension = ".jpg"
            else:  # png
                format_flag = "-png"
                extension = ".png"
            
            # Convert PDF to images
            pdf_result = subprocess.run([
                "pdftoppm", format_flag, "-r", "150",
                str(pdf_path), str(output_prefix)
            ], capture_output=True, text=True, timeout=300)
            
            if pdf_result.returncode != 0:
                raise Exception(f"PDF to image conversion failed: {pdf_result.stderr}")
            
            # Find all generated image files
            image_files = list(temp_dir_path.glob(f"*{extension}"))
            if not image_files:
                raise Exception("No image files were generated")
            
            # Sort files numerically
            image_files.sort(key=lambda x: int(x.stem.split('-')[-1]) if x.stem.split('-')[-1].isdigit() else 0)
            
            # Return list of image file paths
            return [str(file) for file in image_files]
            
    except subprocess.TimeoutExpired:
        raise Exception("Conversion timed out after 5 minutes")
    except Exception as e:
        raise Exception(f"Conversion failed: {str(e)}")

def main():
    if len(sys.argv) < 4:
        print("Usage: python ppt_to_images.py <input_file> <output_format> <quality>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_format = sys.argv[2]
    quality = sys.argv[3]
    
    try:
        if not os.path.exists(input_file):
            raise Exception(f"Input file does not exist: {input_file}")
        
        image_files = convert_ppt_to_images(input_file, output_format, quality)
        print("SUCCESS:" + ",".join(image_files))
        
    except Exception as e:
        print("ERROR:" + str(e))
        sys.exit(1)

if __name__ == "__main__":
    main()
